#!/usr/bin/env php
<?php
require '../vendor/autoload.php';

use Jet\Jet\Commands\RunServer;
use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new Runserver());

$application->run();